type Props = {
  waitlist: any[];
};

export function AiOpsPanel({ waitlist }: Props) {
  const highRisk = waitlist.filter((p) => (p.noshow_prob_current ?? 0) >= 0.6).length;
  const avgEta = waitlist.length
    ? Math.round(
        waitlist.reduce((acc, p) => acc + (p.quoted_wait_minutes ?? 0), 0) / waitlist.length
      )
    : 0;

  return (
    <section className="panel">
      <h2>AI Operations Feed</h2>
      <p className="muted">
        Predictions are generated by backend inference endpoints and used to drive host actions in real time.
      </p>
      <ul>
        <li>Current queue ETA baseline: ~{avgEta} min</li>
        <li>High no-show risk parties needing confirmation: {highRisk}</li>
        <li>Recommended action: trigger "Ready + SMS" early for top-risk parties near front.</li>
      </ul>
    </section>
  );
}
